### 01. Numpy
- 다차원 배열을 쉽고 효율적으로 사용할 수 있도록 지원하는 파이썬 라이브러리
- 데이터 분석 라이브러리의 근본!!  

### 1-1. ndarray
- NymPy의 핵심 데이터 구조
- 동일한 자료형의 다차원 배열

In [23]:
import numpy as np

In [19]:
# ndarray의 생성
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1.0, 3.14, 1.24])

# 배열의 구조
print(f"배열의 구조: {a.shape}")

# 배열의 차원 수 
print(f"배열의 차원: {a.ndim}")

# 데이터 타입
print(f"배열 a의 데이터 타입: {a.dtype}")
print(f"배열 b의 데이터 타입: {b.dtype}")

# 형변환
new_a = a.astype(np.float64)
print(f"배열 new_a의 데이터 타입: {new_a.dtype}")

배열의 구조: (2, 3)
배열의 차원: 2
배열 a의 데이터 타입: int64
배열 b의 데이터 타입: float64
배열 new_a의 데이터 타입: float64


In [14]:
# 3차원 행렬
a = np.array([[[1,2,3],[4,5,6]], 
                [[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6]]])
print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

배열의 구조: (3, 2, 3)
배열의 차원: 3


In [16]:
# 4차원 행렬
a = np.array([[[[1,2,3],[4,5,6]], 
                [[1,2,3],[4,5,6]], 
                [[1,2,3],[4,5,6]],    
                [[1,2,3],[4,5,6]], 
                [[1,2,3],[4,5,6]], 
                [[1,2,3],[4,5,6]]]])
print(f"배열의 구조: {a.shape}")
print(f"배열의 차원: {a.ndim}")

배열의 구조: (1, 6, 2, 3)
배열의 차원: 4


In [18]:
# 만들 수 없는 행렬
# 내부 배열의 구조가 같아야 함.
a = np.array([1, [2,3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### 1-2. 배열 초기화

In [ ]:
# 모든 요소가 0인 배열
np.zeros((3,4))    # 2차원
np.zeros((2,3,4), dtype=np.int64)   # 3차원

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [11]:
# 모든 요소가 1인 배열
np.ones((5,6))     # 2차원

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [12]:
# (원소의 값이) 초기화 되지 않은 배열 생성
np.empty((2,3))

array([[1.04914920e-153, 6.26089492e-143, 3.68977620e+180],
       [4.30512406e-096, 1.50598685e+161, 1.04917752e-153]])

In [17]:
# 주어진 값으로 채운 배열
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
# 단위 행렬
np.eye(3,3)
np.eye(3,5)
np.eye(3,5,1)   # 3번째 인자를 입력 → 1이 오른쪽으로 이동

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
### 1-3. 범위 기반 배열 생성

In [ ]:
# arange : range()와 유사한 기능을 제공
# 시작 이상, 끝 미만의 정수 배열을 지정한 간격으로 생성
np.arange(0,10)
np.arange(0,10,2)   # 간격 지정

array([0, 2, 4, 6, 8])

In [29]:
# linspace : 시작~끝까지 균일 간격으로 지정한 개수만큼 숫자를 생성
# 끝을 포함
np.linspace(10, 100, 10)
np.linspace(0.1, 1, 10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [31]:
# reshape : 배열의 구조를 재배치
np.linspace(1, 10, 6).reshape((2,3))
# np.linspace(1, 10, 10).reshape((2,3))   # 원소의 개수가 같아야 함
np.linspace(5, 100, 20).reshape((4,5))

array([[  5.,  10.,  15.,  20.,  25.],
       [ 30.,  35.,  40.,  45.,  50.],
       [ 55.,  60.,  65.,  70.,  75.],
       [ 80.,  85.,  90.,  95., 100.]])

### 1-4. 랜덤 배열 생성

In [32]:
# random.rand(m, n) : 0~1 사이의 난수로 초기화
np.random.rand(2,3)

array([[0.7131586 , 0.50415358, 0.89527452],
       [0.75240986, 0.84711718, 0.03590392]])

In [4]:
# random.randn(m, n) : 표준정규분포를 따르는 난수로 초기화
# 표준정규분포 : 평균 0, 분산 1인 정규분포
np.random.randn(4,5)
np.random.randn(2,4,5)

# random.normal(평균, 분산, 사이즈)
# 정규분포
np.random.normal(10, 20, (2,4))

array([[ -9.79312615,   0.66737321,   0.19614088, -37.62448743],
       [  4.95891247,  48.09830558,   1.70518987,   3.79563868]])

In [36]:
# random.randint(low, high, (size)) 
np.random.randint(0, 101, (3, 3)) 
print(np.random.randint(0, 101, (3, 3)) )

[[ 32  52  89]
 [ 89  58  52]
 [ 86  39 100]]


In [ ]:
# random.seed() : 난수 생성시 시작값 제공
print(np.random.rand(2,3))
print(np.random.randn(4,5))
print(np.random.randint(0, 101, (3, 3)) )

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439  0.54256004 -0.46341769]
 [-0.46572975  0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037   1.46564877]
 [-0.2257763   0.0675282  -1.42474819 -0.54438272  0.11092259]]
[[50  6 20]
 [72 38 17]
 [ 3 88 59]]


In [6]:
# RNG(Random Number Generator)
# 최근 NumPy 사용에서 권장되는 방식
# 독립적으로 seed를 사용할 수 있음에 장점. (일부는 고정, 일부는 랜덤 생성 가능)

from numpy.random import default_rng
rng = default_rng(seed=42)
rng2 = default_rng(seed=10)
rng3 = default_rng()

print(rng.random((3,2)))    # 0~1 사이의 난수
print(rng.normal(0, 1, (4,5)))  # 정규분포
print(rng2.integers(0, 100, (2,2)))  # 정수 난수
print(rng3.uniform(0, 100, (4,4)))   # 균등분포


[[0.77395605 0.43887844]
 [0.85859792 0.69736803]
 [0.09417735 0.97562235]]
[[ 0.1278404  -0.31624259 -0.01680116 -0.85304393  0.87939797]
 [ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246]
 [ 0.36875078 -0.9588826   0.8784503  -0.04992591 -0.18486236]
 [-0.68092954  1.22254134 -0.15452948 -0.42832782 -0.35213355]]
[[77 95]
 [26 20]]
[[38.63718559 81.49467354 70.07772407 39.68349915]
 [38.32018041 88.56222902 48.43824984 15.6846208 ]
 [20.91407983 53.44722185 47.64380548  5.40199826]
 [50.23953617 75.05727835 82.65224352 23.94102986]]


In [8]:
# 실습. 배열 초기화 및 생성

# 1. 0으로 채워진 크기 (3, 4) 배열을 생성한 후, 모든 값을 5로 채우는 새로운 배열을 만드세요.
a1 = np.zeros((3,4)) 
a1_2 = np.full((3,4), 5)
print("문제1:", a1, a1_2, sep="\n")

# 2. 0부터 20까지 2씩 증가하는 1차원 배열을 생성하세요.
a2 = np.arange(0,21,2)
print("\n 문제2:", a2)

# 3. 0~1 사이의 실수 난수를 가지는 (2, 3) 크기의 배열을 생성하세요.
a3 = np.random.rand(2,3)
print("\n 문제3:", a3)

# 4. 평균이 100, 표준편차가 20인 정규분포 난수 6개를 생성하세요.
a4 = rng.normal(100, 20, 6)
print("\n 문제4:", a4)

# 5. 1부터 20까지의 정수를 포함하는 1차원 배열을 만들고, 이 배열을 (4, 5) 크기의 2차원 배열로 변환하세요.
a5 = np.arange(1,21).reshape((4,5))
print("\n 문제5:", a5)

# 6. 0부터 1까지 균등 간격으로 나눈 12개의 값을 가지는 배열을 생성하고, 이를 (3, 4) 크기로 변환하세요. 
a6 = np.linspace(0, 1, 12).reshape((3,4))
print("\n 문제6:", a6)

# 7. 0~99 사이의 정수 난수로 이루어진 (10, 10) 배열을 생성한 뒤, 
#   np.eye()로 만든 단위 행렬을 더하여 대각선 요소가 1씩 증가된 배열을 만드세요.
a7 = np.random.randint(0, 100, (10, 10)) 
a7_eye = np.eye(10,10)
a7_added = a7 + a7_eye
print("\n 문제7:", a7_added)

# 8.  0~9 사이의 정수 난수로 이루어진 (2, 3, 4) 3차원 배열을 생성하세요
a8 = np.random.randint(0, 10, (2,3,4)) 
print("\n 문제8:", a8)

문제1:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

 문제2: [ 0  2  4  6  8 10 12 14 16 18 20]

 문제3: [[0.70904629 0.05264375 0.76407221]
 [0.14601656 0.19406248 0.49299971]]

 문제4: [ 89.75514542  83.72454544 112.31958845 122.57944585  97.72105085
  83.19687046]

 문제5: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 문제6: [[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]

 문제7: [[64. 29. 52. 65. 42. 79. 33. 28. 70. 89.]
 [23. 21. 94. 23. 45. 72. 82. 34. 83.  1.]
 [99. 17. 94. 84.  7. 36. 42. 92. 11. 27.]
 [35. 77. 23. 19. 96. 57. 42. 60. 23. 39.]
 [17. 20.  4. 33. 92. 67.  1. 81. 50. 43.]
 [21. 66. 36. 12. 95. 34. 39. 69. 11. 34.]
 [42. 55.  5.  1. 83.  2. 64. 26. 84. 72.]
 [86. 16. 56. 45. 46. 62. 27.  9. 18. 72.]
 [90.  8. 21. 54. 98. 19. 38. 39. 35. 76.]
 [ 9. 67. 74. 56. 69. 63. 83. 61. 18. 38.]]

 문제8: [[[6 7 7 2]
  [9 4 2 1]
  [0 8 

### 1-5. 인덱싱과 슬라이싱 
- 다차원 배열을 다루는 편의 기능 제공
- Python의 시퀀스보다 빠름

In [10]:
# 인덱싱
a = np.array([10,20,30,40,50])
print(a[2])
print(a[-1])

30
50


In [15]:
# 다차원 인덱싱

# 파이썬 리스트
matrix = [[1,2,4],[4,5,6]]
print("파이썬 인덱싱:", matrix[1][1])

# NumPy 배열
a2 = np.array( [[1,2,4],[4,5,6]])
print("numpy 인덱싱:", a2[1,2])

파이썬 인덱싱: 5
numpy 인덱싱: 6


In [13]:
# 3차원 배열 인덱싱
a3 = np.arange(24).reshape(2,3,4)
print(a3)
print("17찾기:", a3[1,1,1])
print("11찾기:", a3[0,2,3])
print("23찾기:", a3[1,2,3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
17찾기: 17
11찾기: 11
23찾기: 23


In [ ]:
# 슬라이싱
# arr[행_슬라이스, 열_슬라이스]
# arr[..., 4차원슬라이스, 3차원슬라이스, 2차원슬라이스, 1차원슬라이스]
a1 = np.array([10,20,30,40,50])
print(a1[1:3])
print(a1[2:])
print(a1[:3])
print(a1[::2])
print(a1[::-1])

[20 30]
[30 40 50]
[10 20 30]
[10 30 50]


In [ ]:
# 파이썬 리스트와의 차이

# 파이썬 리스트
py_list = [10,20,30,40,50]
sliced = py_list[1:4]
sliced[1] = 100
print("python 원본:", py_list)
print("python 슬라이싱:", sliced)
print()

# NumPy 배열
a1 = np.array([10,20,30,40,50])
a1_sliced = a1[1:4]
a1_sliced[1] = 100
print("numpy 원본:", a1)
print("numoy 슬라이싱:", a1_sliced)


python 원본: [10, 20, 30, 40, 50]
python 슬라이싱: [20, 100, 40]

numpy 원본: [ 10  20 100  40  50]
numoy 슬라이싱: [ 20 100  40]


In [32]:
# 2차원 배열 슬라이싱
a2 = np.arange(1,21).reshape(4,5)
print("원본:", a2)
print()

# 행 슬라이싱(2차원 슬라이싱)
print(a2[0, :])
print(a2[0])
print(a2[1])
print(a2[1:3])
print(a2[2:])
print()

# 열 슬라이싱(1차원 슬라이싱)
print(a2[:, 2])
print(a2[:, -1])
print(a2[:, 1:3])
print()

# 행과 열 슬라이싱
print(a2[1:3, 2:4])
print(a2[2:, 3:])
print(a2[::2, ::2])

원본: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

[1 2 3 4 5]
[1 2 3 4 5]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[11 12 13 14 15]
 [16 17 18 19 20]]

[ 3  8 13 18]
[ 5 10 15 20]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]]

[[ 8  9]
 [13 14]]
[[14 15]
 [19 20]]
[[ 1  3  5]
 [11 13 15]]


In [35]:
# 3차원 슬라이싱
a3 = np.arange(36).reshape(3,3,4)
print("원본:", a3)
print()
print(a3[1,1,1:3])

원본: [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]]

[17 18]


In [40]:
# 얕은 복사 : 복사본이 원본과 메모리를 공유 → 변경사항이 서로에게 영향을 줌
a1 = np.array([1,2,3])
a1_copied = a1.view()
a1_copied[1] = 10
print("원본", a1)
print("복사본", a1_copied)
print()

# 깊은 복사: 복사본이 원본과 독립적으로 복사됨 → 서로 영향을 주지 x
a2 = np.array([1,2,3])
a2_copied = a2.copy()
a2_copied[1] = 10
print("원본", a2)
print("복사본", a2_copied)

원본 [ 1 10  3]
복사본 [ 1 10  3]

원본 [1 2 3]
복사본 [ 1 10  3]


In [51]:
# Fancy Indexing
# 정수 배열을 사용하여 여러 인덱스로 여러 요소를 한번에 선택
af = np.arange(1,21)
print(af)
print(af[[4,7,11]])

af2 = np.arange(1,21).reshape(4, 5)
print(af2)
print(af2[[1,3],[2,4]])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 5  8 12]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[ 8 20]


In [47]:
# Boolean Indexing
ab = np.linspace(10,100,10)
print(ab)
print(ab[ab > 40])
print()

# Boolean masking
ab2 = np.arange(0,21)
print(ab2)
mask = ab2 % 2 == 0
print(mask)
print(ab2[mask])

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 50.  60.  70.  80.  90. 100.]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
# 1. 다음 배열에서 2, 4, 6번째 요소를 Fancy Indexing으로 선택하세요.
arr = np.arange(10, 30, 2)
print("✔ 문제1:", arr[[1,3,5]])
print()
# 2. 3x3 배열에서 왼쪽 위 → 오른쪽 아래 대각선의 요소만 인덱싱으로 추출하세요.
arr = np.arange(1, 10).reshape(3, 3)
print("✔ 문제2:", arr[[0,1,2],[0,1,2]])
print()
# 3. 3x4 배열에서 마지막 열만 선택해 모두 -1로 변경하세요.
arr = np.arange(1, 13).reshape(3, 4)
arr[:,-1] = -1
print("✔ 문제3:\n", arr)
print()
# 4. 4x4 배열에서 행을 역순, 열을 역순으로 각각 슬라이싱해 출력하세요.
arr = np.arange(1, 17).reshape(4, 4)
print("✔ 문제4 - 행 역순:\n", arr[::-1])
print("✔ 문제4 - 열 역순:\n", arr[:,::-1])
print()
# 5. 4x5 배열에서 가운데 2x3 부분을 슬라이싱한 뒤 copy()를 이용해 독립 배열을 만드세요.
arr = np.arange(1, 21).reshape(4, 5)
arr_copied = arr.copy()
print("✔ 문제5:\n", arr_copied[1:3,1:4])
print()
# 6. 3x4 배열에서 짝수이면서 10 이상인 값만 선택하세요
arr = np.array([[ 4, 9, 12, 7], [10, 15, 18, 3], [ 2, 14, 6, 20]])
mask_1 = arr % 2 == 0 
mask_2 = arr >= 10
print("✔ 문제6:",arr[mask_1 & mask_2])
# 다른 풀이: arr[(arr%2 ==0)&(arr>=10)]
print()
# 7. 방법 1. 5x5 배열에서 2, 4번째 행을 선택하고, 선택된 행에서 열 순서를 [4, 0, 2]로 재배치하세요.
arr = np.arange(1, 26).reshape(5, 5)
result = arr[[1,3]]
answer = []
for i in result:
    answer.append([i[4],i[0],i[2]])
print("✔ 문제7-1:\n",np.array(answer))
# 7. 방법 2
arr = np.arange(1, 26).reshape(5, 5)
result = arr[[1,3]]
result[:,[4,0,2]]
print("✔ 문제7-2:\n",result)
print()
# 8. 5x3 배열에서 각 행의 첫 번째 값이 50 이상인 행만 Boolean Indexing으로 선택하세요.
arr = np.array([[10, 20, 30], [55, 65, 75], [40, 45, 50], [70, 80, 90], [15, 25, 35]])
print("✔ 문제8:\n", arr[arr[:,0] >= 50])
print()
# 9. 4x4 배열에서 (0,1), (1,3), (2,0), (3,2) 위치의 요소를 한 번에 선택하세요.
arr = np.arange(1, 17).reshape(4, 4)
print("✔ 문제9:",arr[[0,1,2,3],[1,3,0,2]])
print()
# 10. 3차원 배열 (2, 3, 4)에서 모든 블록에서 두 번째 열만 추출해 새로운 2차원 배열 (2, 3)을 만드세요.
arr3d = np.arange(24).reshape(2, 3, 4)
print("✔ 문제10:\n", arr3d[:,:,1])

✔ 문제1: [12 16 20]

✔ 문제2: [1 5 9]

✔ 문제3:
 [[ 1  2  3 -1]
 [ 5  6  7 -1]
 [ 9 10 11 -1]]

✔ 문제4 - 행 역순:
 [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
✔ 문제4 - 열 역순:
 [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]

✔ 문제5:
 [[ 7  8  9]
 [12 13 14]]

✔ 문제6: [12 10 18 14 20]

✔ 문제7-1:
 [[10  6  8]
 [20 16 18]]
✔ 문제7-2:
 [[ 6  7  8  9 10]
 [16 17 18 19 20]]

✔ 문제8:
 [[55 65 75]
 [70 80 90]]

✔ 문제9: [ 2  8  9 15]

✔ 문제10:
 [[ 1  5  9]
 [13 17 21]]


In [ ]:
# 1. 0부터 24까지 정수를 가진 배열을 만들고, (5, 5) 배열로 변환한 뒤 가운데 행(3번째 행)과 가운데 열(3번째 열)을 각각 1차원 배열로 출력하세요
arr = np.arange(0,25).reshape(5,5)
print("문제1.")
print("가운데 행:", arr[2])
print("가운데 열:",arr[:,2])
print()
# 2.  0~99 정수 난수로 이루어진 (10, 10) 배열을 생성하고, 짝수 인덱스의 행만 선택하여 출력하세요.
arr = np.random.randint(0,100,(10,10))
print("문제2.\n짝수 인덱스 행:\n", arr[::2])
print()
# 3. 0부터 49까지 정수를 가진 배열을 (5, 10) 배열로 변환한 후, 2행 3열부터 4행 7열까지의 부분 배열을 추출하세요.
arr = np.arange(0,50).reshape(5,10)
print("문제3.\n부분배열:\n",arr[1:4,2:7])
print()
# 4. 0~9 난수로 이루어진 (4, 4) 배열을 생성하고, 각각 인덱싱으로 추출해 출력하세요.(for 이용)
a4 = np.random.randint(0,10,(4,4))
print("문제4.\n주대각선: ", a4[[0,1,2,3],[0,1,2,3]])
print("부대각선: ", a4[[0,1,2,3],[3,2,1,0]])
print()
# 5. 0~9 난수로 이루어진 (3, 4, 5) 3차원 배열을 생성하고, 두 번째 층에서 첫 번째 행과 마지막열의 값을 출력하세요.
arr = np.random.randint(0,10,(3,4,5))
print("문제5.\n두 번째 층의 첫 행 마지막 열 값:", arr[1,0, -1])
print()
# 6. 35부터 74까지의 순차적인 수로 이루어진 1차원 배열을 만들고 10x4 행렬로 변환 후 출력해주세요.
arr = np.arange(35,75)
arr6 = arr.reshape(10,4)
print("문제6.\n",arr6)
print()
# 7. 6번에서 만든 배열을 맨 끝의 행부터 역순으로 출력해주세요.
print("문제7.\n",arr6[::-1])
print()
# 8. 6번에서 만든 배열 중 두 번째 행부터 마지막 직전 행까지, 세번째 열부터 마지막 열까지 슬라이싱해서 출력해주세요.

# 9. 1부터 50까지의 난수로 된 5x6 배열을 만들고, 배열에서 짝수만 선택하여 출력하는 코드를 작성하세요.

# 10. 0부터 99까지의 정수로 이루어진 (10, 10) 배열을 생성한 후, [1, 3, 5]번째 행과 [2, 4, 6]번째 열의 교차하는 원소들만 선택하여 출력하세요. 

# 11.  0~9 난수로 이루어진 1차원 배열(길이 15)을 생성하고, 짝수 인덱스 위치에 있는 값들 중에서 5 이상인 값만 선택해 출력하세요.


문제1.
가운데 행: [10 11 12 13 14]
가운데 열: [ 2  7 12 17 22]

문제2.
짝수 인덱스 행:
 [[74  9 61 21 39 43 88 50 66 45]
 [36 48 76 62 27 43 98 87 36  5]
 [81 41  1 72 58 13  0 93 77 11]
 [82 80 45 75 72 99 53 88  8  6]
 [51 67 96 57 19 96 37 53 37 86]]

문제3.
부분배열:
 [[12 13 14 15 16]
 [22 23 24 25 26]
 [32 33 34 35 36]]

문제5.
두 번째 층의 첫 행 마지막 열 값: 3

문제6.
 [[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]

문제7.
 [[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]



In [164]:
arr = np.arange(35,75)
arr6 = arr.reshape(10,4)
print(arr6)

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]


In [ ]:
# 문제 4.
a4 = np.random.randint(0,10,(4,4))
print("주대각선: ", a4[[0,1,2,3],[0,1,2,3]])
print("주대각선: ", a4[[0,1,2,3],[3,2,1,0]])


[[5 5 3 3]
 [8 8 9 2]
 [1 4 2 1]
 [1 4 4 4]]
