### 2-1. Numpy 배열 연산

In [101]:
import numpy as np

In [ ]:
# 배열 간 연산(1차원) 
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(a1 + a2)
print(a1 - a2)

[5 7 9]
[-3 -3 -3]


In [ ]:
# 배열 간 연산(2차원) 
a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(11,15).reshape(2,2)

print(a1)
print(a2)
print(a1 + a2)
print(a1 - a2)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[12 14]
 [16 18]]
[[-10 -10]
 [-10 -10]]


In [ ]:
# 배열과 스칼라 연산(1차원) 
a1 = np.array([1,2,3,4])
print(a1 + 10)
print(a1 * 2)

[11 12 13 14]
[2 4 6 8]


In [10]:
# 배열과 스칼라 연산(2차원) 
a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(11,15).reshape(2,2)

print(a1)
print(a2)
print(a1 + 5)
print(a2 * 3)
print(a2 // 2)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[6 7]
 [8 9]]
[[33 36]
 [39 42]]
[[5 6]
 [6 7]]


In [13]:
# 브로드캐스팅 
# : 자동으로 배열의 크기를 확장 → 서로 다른 크기의 배열 간 연산을 가능하게 하는 기능
# 1. 두 배열의 차원을 뒤(낮은 차원)에서부터 비교
# 2. 크기가 같거나
# 3. 한쪽이 1인 경우 확장이 가능

a1 = np.array([[1,2,3],[4,5,6]]) # 2x3 배열
a2 = np.array([10,20,30]) # 길이가 3인 1차원 배열

# 1차원 길이 3
[10,20,30]
# 2차원으로 변형 (1,3)
[[10,20,30]]
# 2차원의 행의 행이 2로 확장
[[10,20,30], [10,20,30]]

print(a1 + a2)

[[11 22 33]
 [14 25 36]]


In [49]:
# 브로드 캐스팅 예제
a1 = np.array ([[1],[2],[3]])  # (3, 1)
a2 = np.array([10, 20, 30])  # (3,)
print("a1 shape:", a1.shape)
print("a2 shape:", a2.shape)
print()
# a2 : (3,) → (1, 3)로 변형
[[10, 20, 30]]

# a1과 a2의 비교: a1 = (3, 1), a2 = (1, 3)
# 2차원의 경우 : 3 vs 1 → a2의 2차원이 3으로 확장
[[10,20,30], [10,20,30], [10,20,30]]

# 1차원의 경우 : 1 vs 3 → a1의 1차원이 3으로 확장
[[1,1,1], [2,2,2], [3,3,3]]

# a1 
[[1,1,1], [2,2,2], [3,3,3]]
# a2 
[[10,20,30], [10,20,30], [10,20,30]]

print(a1 + a2)

a1 shape: (3, 1)
a2 shape: (3,)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# 브로드캐스팅 불가능한 경우
# 마지막 차원도 다르고, 1도 아님
a1 = np.ones((2,3))
a2 = np.ones((3,2))

print(a1 + a2)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [48]:
# 실습. 배열연산
# 1. 다음 배열을 생성하고, 모든 요소에 3을 더하세요
arr = np.array([1, 2, 3, 4])
a1 = arr +3
print("문제 1.\n", a1)
# 2. 아래 2차원 배열에서 각 요소를 -1로 곱한 새로운 배열을 만드세요.
arr = np.array([[5, 10],
[15, 20]])
a2 = arr * -1
print("문제 2.\n", a2)
# 3. 아래 두 배열의 요소별 곱셈과 나눗셈 결과를 각각 출력하세요.
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 2, 3])
print("문제 3.\n", arr1 * arr2)
print("",arr1 / arr2)
# 4. 아래 배열에서 모든 요소를 최대값 100으로 만들기 위해 
#    필요한 값을 더한 결과 배열을 브로드캐스팅으로 만드세요.
arr = np.array([[95, 97],
[80, 85]])
need = 100 - arr
print("문제 4.")
print("- 필요한 값:")
print(need)
print("- 원래 배열 + 필요한 값:")
print(arr + need)
# 5. 아래 2차원 배열에서 각 행에 다른 값을 곱하여 새로운 배열을 만드세요.(브로드캐스팅 이용)
arr = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10],[100]])
print("문제 5.\n",arr * arr2)
# 6. 아래 배열에서 각 행마다 다른 스칼라 값을 더하기 위해
#   • 첫 번째 행에 100, 두 번째 행에 200, 세 번째 행에 300을 더하세요.
arr = np.array([[10, 20],
[30, 40],
[50, 60]])
arr2 = np.array([[100],[200],[300]])
print("문제 6.\n",arr + arr2)

문제 1.
 [4 5 6 7]
문제 2.
 [[ -5 -10]
 [-15 -20]]
문제 3.
 [ 2  8 18]
 [2. 2. 2.]
문제 4.
- 필요한 값:
[[ 5  3]
 [20 15]]
- 원래 배열 + 필요한 값:
[[100 100]
 [100 100]]
문제 5.
 [[ 10  20  30]
 [400 500 600]]
문제 6.
 [[110 120]
 [230 240]
 [350 360]]


### 2-2. 통계 함수 및 집계 연산

In [ ]:
a = np.array([[1,2,3],[4,5,6]])

print("원소의 합:", np.sum(a))
print("원소의 평균:", np.mean(a))
print("원소의 표준편차:", np.std(a))
print("원소의 최댓값:", np.max(a))
print("원소의 최솟값:", np.min(a))
print("원소의 최댓값의 인덱스:", np.argmax(a))
print("원소의 최솟값의 인덱스:", np.argmin(a))


원소의 합: 21
원소의 평균: 3.5
원소의 표준편차: 1.707825127659933
원소의 최댓값: 6
원소의 최솟값: 1
원소의 최댓값의 인덱스: 5


In [ ]:
# 축(axis) 단위 연산 
# aixs = 0 → 가장 높은 차원 기준 → 행기준
    # 행기준 = 행을 따라 연산 = 행을 증가시키며 연산
# aixs = 1 → 그 다음 차원 기준 → 열기준
    # 열기준 = 열을 따라 연산 = 열을 증가시키며 연산

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("행기준합: ",np.sum(a, axis=0))
print("열기준합: ",np.sum(a, axis=1))
print("행기준평균: ",np.mean(a, axis=0))
print("열기준평균: ",np.mean(a, axis=1))


행기준합:  [12 15 18]
열기준합:  [ 6 15 24]
행기준평균:  [4. 5. 6.]
열기준평균:  [2. 5. 8.]


In [61]:
# 누적 연산
arr = np.array([1,2,3,4])
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 1  3  6 10]
[ 1  2  6 24]


In [78]:
# 실습. 통계 함수 및 집계 연산
# 1. 아래 배열의 전체 합계와 평균을 각각 구하세요.
arr = np.array([5, 10, 15, 20])
print("문제1.\n- 합:", np.sum(arr))
print("- 평균:", np.mean(arr))
# 2. 다음 2차원 배열에서 전체 최소값과 최대값을 구하세요.
arr = np.array([[3, 7, 1], [9, 2, 8]])
print("문제2.\n- 최솟값:", np.min(arr))
print("- 최댓값:", np.max(arr))
# 3. 아래 배열에서 각 열의 합계와 각 행의 합계를 각각 구하세요.
arr = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print("문제3.\n- 각 열의 합계:", np.sum(arr, axis=0))
print("- 각 행의 합계:", np.sum(arr, axis=1))
# 4. 아래 배열에서 행별 평균과 열별 평균을 각각 구하세요.
arr = np.array([[10, 20], [30, 40], [50, 60]])
print("문제4.\n- 행별 평균:", np.mean(arr, axis=1))
print("- 열별 평균:", np.mean(arr, axis=0))
# 5. 1차원 배열에서 전체 표준편차를 구하고,
#    각 요소가 평균으로부터 얼마나 떨어져 있는지 편차배열을 만드세요. (값 - 평균)
arr = np.array([2, 4, 4, 4, 5, 5, 7, 9])
print("문제5.\n- 표준편차:", np.std(arr))
print("- 편차배열:", arr - np.mean(arr) )
# 6. 아래 2차원 배열에서 행 단위 누적 합과 열 단위 누적 곱을 각각 구하세요.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("문제6.\n- 행 단위 누적 합:\n", np.cumsum(arr, axis = 1))
print("- 열 단위 누적 곱:\n",np.cumprod(arr, axis =0))

문제1.
- 합: 50
- 평균: 12.5
문제2.
- 최솟값: 1
- 최댓값: 9
문제3.
- 각 열의 합계: [12 15 18]
- 각 행의 합계: [ 6 15 24]
문제4.
- 행별 평균: [15. 35. 55.]
- 열별 평균: [30. 40.]
문제5.
- 표준편차: 2.0
- 편차배열: [-3. -1. -1. -1.  0.  0.  2.  4.]
문제6.
- 행 단위 누적 합:
 [[ 1  3  6]
 [ 4  9 15]]
- 열 단위 누적 곱:
 [[ 1  2  3]
 [ 4 10 18]]


### 2-3. 논리 연산과 조건 연산

In [79]:
# np.where()
# 조건 기반 선택 함수

arr = np.array([10,20,30,40,50])
result = np.where(arr > 30, "High", "Low")
print(result)

['Low' 'Low' 'Low' 'High' 'High']


In [ ]:
arr = np.array([10,20,30,40,50])
# 조건만 넣을 경우 조건을 만족하는 원소의 인덱스를 반환
result = np.where(arr > 30)
print(result)
print(arr[result])  # 원본 배열에 Fancy indexing

(array([3, 4]),)


In [ ]:
# 논리 연산
# and : & → 모든 조건이 True여야 True
# or : | → 조건 중 하나라도 True면 True
# not : ~ → True를 False로, False를 True로

# and 연산(&) 
arr = np.array([10,20,30,40,50])
mask = (arr > 10) & (arr < 50)
print(mask)
print("&연산: ", arr[mask])

# or 연산(|) 
mask_or = (arr < 20) | (arr > 40)
print("|연산: ", arr[mask_or])

# not 연산(~)
mask_not = ~(arr > 30)
print("~연산: ", arr[mask_not])


[False  True  True  True False]
&연산:  [20 30 40]
|연산:  [10 50]
~연산:  [10 20 30]


In [83]:
arr = np.arange(0,100)
mask = (arr % 2 == 0) & (arr > 50)
print(arr[mask])

[52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


In [100]:
# 실습. 논리 연산과 조건 연산
# 1. 1차원 배열 [5, 12, 18, 7, 30, 25]에서 10보다 크고 20보다 작은 값만 필터링하세요.
arr = np.array([5, 12, 18, 7, 30, 25])
mask = (arr > 10) & (arr < 20)
print("문제 1.\n", arr[mask])
# 2. 0배열 [10, 15, 20, 25, 30, 35]에서 15 이하이거나 30 이상인 값만 선택하세요
arr = np.array([10, 15, 20, 25, 30, 35])
mask = (arr <= 15) | (arr >= 30)
print("문제 2.\n", arr[mask])
# 3. 배열 [3, 8, 15, 6, 2, 20]에서 10 이상인 값을 모두 0으로 변경하세요.
arr = np.array([3, 8, 15, 6, 2, 20])
print("문제 3.\n", np.where(arr >= 10, 0, arr))
# 다른 방법:
# arr[arr >= 10] = 0
# print(arr)
# 4. 배열 [7, 14, 21, 28, 35]에서 20 이상인 값은 "High", 나머지는 "Low"로 표시하는 새로운 배열을 생성하세요.
arr = np.array([7, 14, 21, 28, 35])
print("문제 4.\n",np.where(arr >= 20, "High", "Low"))
# 5. 0~9 범위의 배열에서 짝수는 그대로 두고, 홀수는 홀수 값 × 10으로 변환한 배열을 만드세요
arr = np.arange(0,10)
print("문제 5.\n", np.where(arr % 2 ==0, arr, arr * 10))
# 6. 아래 2차원 배열 에서 20 이상 40 이하인 값만 선택하세요.
arr = np.array([[10, 25, 30],
        [40, 5, 15],
        [20, 35, 50]])
mask = (arr >= 20) & (arr <= 40)
print("문제 6.\n", arr[mask])
# 7. 배열 [1, 2, 3, 4, 5, 6]에서 3의 배수가 아닌 값만 선택하세요.
arr = np.array([1, 2, 3, 4, 5, 6])
mask = ~(arr % 3 == 0)
print("문제 7.\n", arr[mask])
# 8. 랜덤 정수(0~100) 10개 배열에서 아래와 같이 새로운 배열을 만드세요.
#   • 50 이상인 값은 그대로
#   • 50 미만인 값은 50으로 변경
arr_rand = np.random.randint(0, 101, size=10)
print("문제 8.\n", np.where(arr_rand >= 50, arr_rand, 50))
# 9. 2차원 배열에서 아래와 같이 분류된 문자열 배열을 생성하세요.
#   • 70 이상 → "A"
#   • 30 이상 70 미만 → "B"
#   • 30 미만 → "C“
arr = np.array([[5, 50, 95],
                [20, 75, 10],
                [60, 30, 85]])
print("문제 8.\n",  np.where(arr >= 70, "A", 
                           np.where(arr>= 30, "B", "C")))

문제 1.
 [12 18]
문제 2.
 [10 15 30 35]
문제 3.
 [3 8 0 6 2 0]
문제 4.
 ['Low' 'Low' 'High' 'High' 'High']
문제 5.
 [ 0 10  2 30  4 50  6 70  8 90]
문제 6.
 [25 30 40 20 35]
문제 7.
 [1 2 4 5]
문제 8.
 [50 50 96 50 97 68 50 51 50 50]
문제 8.
 [['C' 'B' 'A']
 ['C' 'A' 'C']
 ['B' 'B' 'A']]


### 2-4. 행렬 곱셈
- 두 행렬을 곱해서 새로운 행렬을 생성하는 연산
- 첫번째 행렬의 열수와 두번째 행렬의 행수가 같아야 곱셈이 가능
- np.dot(), np.matmul() → 행렬의 곱셈의 경우 matmul 사용을 권장

In [ ]:
# np.dot(a,b) : 배열의 내적 연산
# 스칼라 연산
a = np.array(3)
b = np.array(4)
print(np.dot(a,b))

12


In [ ]:
# 1차원 배열 간 연산 → 내적
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))

# 물건 구매
# 데이터 분석에서 벡터란 배열
c = [1000, 2000,5000, 10000]
d = [10, 3, 5, 7]
print(np.dot(c,d))

32
111000


In [107]:
# 2차원 배열 간 연산 → 행렬 곱셈
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2], [3,4], [5,6]])
print(np.dot(a,b))

[[22 28]
 [49 64]]


In [108]:
# np.matmul(a,b)
# Matrix Multiplication
# 스칼라 연산 시도시 에러
a = np.array(3)
b = np.array(4)
print(np.matmul(a,b))

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
# 1차원 배열 간 연산 → 내적
a = np.array([1,2])
b = np.array([3,4])
print(np.matmul(a,b))

11


In [ ]:
# 2차원 배열 간 연산 → 행렬 곱셈
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,2], [3,4], [5,6]])
print(np.matmul(a,b))
print()

# 2d * 1d 간 연산
c = np.array([[1,2], [3,4]])
d = np.array([5,6])
print(np.matmul(c,d))
print(np.matmul(d,c))
print()

# @ 연산자
e = np.array([1,2,3])
f = np.array([[1,2], [3,4], [5,6]])
print(np.matmul(e,f))
print(e @ f)

[[22 28]
 [49 64]]

[17 39]
[23 34]

[22 28]
[22 28]


In [138]:
# 실습. 행렬 곱셈
# 1. 1부터 9까지의 정수로 채워진 (3, 3) 배열 A와, 모두 2로 채워진 (3, 2) 배열 B를 만들고 곱하세요.
a = np.arange(1,10).reshape(3,3)
b = np.full((3,2), 2)
print("문제1.\n", np.dot(a,b))
print()
# 2. 4×4 단위행렬 I와, 4×4 난수 행렬 M(0~9 사이 정수) 간의 곱을 구하고, 결과와 M이 동일한지 확인하세요
i = np.eye(4)
m = np.random.randint(0, 10, (4,4))
print("문제2.\nI x M:\n", np.matmul(i,m))
print("M:\n", m)
#   + 같은 위치에 있는 원소끼리 곱함
#   print("m*i:\n",m*i)
print()
# 3.  모든 값이 1인 (2, 5) 배열 X와, 5부터 14까지의 연속된 정수로 채워진 (5, 2) 배열 Y를 만들어 곱하세요.
x = np.ones((2,5))
y = np.arange(5,15).reshape(5,2)
print("문제3.\n", x @ y)
print()
# 4. 0 이상 5 미만의 임의의 정수로 채워진 (3, 2) 배열 C와 (2, 3) 배열 D를 각각 만들어 곱한 결과의 shape와 값을 출력하세요.
c = np.random.randint(0, 5, (3,2))
d = np.random.randint(0, 5, (2,3))
print("문제4.\n", c @ d)
print("shape:\n", np.matmul(c,d).shape)

문제1.
 [[12 12]
 [30 30]
 [48 48]]

문제2.
I x M:
 [[2. 4. 5. 0.]
 [4. 2. 7. 1.]
 [2. 9. 6. 6.]
 [2. 1. 1. 5.]]
M:
 [[2 4 5 0]
 [4 2 7 1]
 [2 9 6 6]
 [2 1 1 5]]

문제3.
 [[45. 50.]
 [45. 50.]]

문제4.
 [[12  9 12]
 [ 6  8  0]
 [ 3  4  0]]
shape:
 (3, 3)
