## Numpy(3)

### 3-1. 배열의 형태 변형과 차원 확장/축소

In [1]:
import numpy as np

In [22]:
# array.ravel()
# 다차원 배열을 1차원 배열로 펼침
# 결과를 view로 반환(view를 변경 시 원본도 변경)
a = np.array([[1,2,3], [4,5,6]])
print("✔ 다차원 배열:\n", a)
flat = a.ravel()
print("✔ 1차원으로 펼침:\n", flat)
flat[2] = 100
print("✔ flat 수정:\n",flat)
print("✔ 원본도 변경:\n", a)

✔ 다차원 배열:
 [[1 2 3]
 [4 5 6]]
✔ 1차원으로 펼침:
 [1 2 3 4 5 6]
✔ flat 수정:
 [  1   2 100   4   5   6]
✔ 원본도 변경:
 [[  1   2 100]
 [  4   5   6]]


In [19]:
# array.flatten()
# 다차원 배열을 1차원 배열로 펼침
# 결과를 복사본으로 봔혼(복사본 변경 시 원본은 변경되지 않음)
a = np.array([[[1,2], [4,5]],[[6,7], [8,9]]])
print("✔ 다차원 배열:\n", a)
print()
flat = a.flatten()
print("✔ 1차원으로 펼침:\n", flat)
print()
flat[4] = 0
print("✔ flat 수정:\n", flat)
print()
print("✔ 원본 변경 x:\n", a)

✔ 다차원 배열:
 [[[1 2]
  [4 5]]

 [[6 7]
  [8 9]]]

✔ 1차원으로 펼침:
 [1 2 4 5 6 7 8 9]

✔ flat 수정:
 [1 2 4 5 0 7 8 9]

✔ 원본 변경 x:
 [[[1 2]
  [4 5]]

 [[6 7]
  [8 9]]]


In [ ]:
# np.expand_dims(a, axis)
# 지정한 위치에 차원 추가 (차원 확장)
# 추가되는 차원은 1
a = np.array([[1,2,3], [4,5,6]]) # 2 x 3
print("✔ 원본 shape:", a.shape)
print()
# axis=0
a0 = np.expand_dims(a, axis=0)
print("✔ a0 shape:", a0.shape)
print("✔ a0:\n",a0)
print()
# axis=1
a1 = np.expand_dims(a, axis=1)
print("✔ a1 shape:", a1.shape)
print("✔ a1:\n", a1)
print()
# axis=2
a2 = np.expand_dims(a, axis=2)
print("✔ a2 shape:", a2.shape)
print("✔ a2:\n", a2)

✔ 원본 shape: (2, 3)

✔ a0 shape: (1, 2, 3)
✔ a0:
 [[[1 2 3]
  [4 5 6]]]

✔ a1 shape: (2, 1, 3)
✔ a1:
 [[[1 2 3]]

 [[4 5 6]]]

✔ a2 shape: (2, 3, 1)
✔ a2:
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [ ]:
# np.squeeze(a, axis=None)
# 배열에서 크기가 1인 차원을 제거해주는 함수

# axis를 지정하지 않는 경우
a = np.array([[[[1],[2],[3]]], [[[1],[2],[3]]]])
print(a.shape)
s = np.squeeze(a)
print(s)
print(s.shape)

(2, 1, 3, 1)
[[1 2 3]
 [1 2 3]]
(2, 3)


In [33]:
# axis를 지정하는 경우
a2 = np.zeros((1,4,1,2))
print("✔ 원본 shape:",a2.shape)

s1 = np.squeeze(a2, axis=0)
print("✔ axis = 0 shape:",s1.shape)

s2 = np.squeeze(a2, axis=2)
print("✔ axis = 2 shape:",s2.shape)

# 차원의 크기가 1이 아닌 차원은 제거할 수 x
# s3 = np.squeeze(a2, axis=1)

✔ 원본 shape: (1, 4, 1, 2)
✔ axis = 0 shape: (4, 1, 2)
✔ axis = 2 shape: (1, 4, 2)


In [ ]:
# np.unique()
# 배열에서 중복된 요소를 제거
a = np.array([1,1,1,1,2,5,2,2,3,3,4,4,5,6,6,7,7,4,3,2,2,5,8])
u1 = np.unique(a) # 고유값의 오름차순 배열 반환
print(u1)

u2, idx, inv, cnt = np.unique(a, return_index=True, return_inverse=True, return_counts=True)
print("인덱스:", idx)   # 고유값이 원본에서 처음 나타나는 인덱스
print("원본의 고유값 인덱스:", inv)
print("값의 등장 횟수:", cnt)


[1 2 3 4 5 6 7 8]
인덱스: [ 0  4  8 10  5 13 15 22]
원본의 고유값 인덱스: [0 0 0 0 1 4 1 1 2 2 3 3 4 5 5 6 6 3 2 1 1 4 7]
값의 등장 횟수: [4 5 3 3 3 2 2 1]


In [71]:
# 실습. 배열 형태 변형, 차원 확장·축소
# 1. 아래의 배열을 사용해서
#   1) ravel과 flatten을 각각 사용해 1차원 배열로 변환하고,
#   2) arr의 첫 번째 원소(arr[0,0])를 999로 바꾼 뒤 ravel 결과와 flatten 결과에 어떤 변화가 있는지 확인하세요.
arr = np.array([[10, 20], [30, 40], [50, 60]])
r = arr.ravel()
f = arr.flatten()
print("✔문제1\n -r:", r)
print(" -f:",f)
arr[0,0]=999
print(" -r 수정 후:",r)
print(" -f 수정 후:",f)
# 2. 크기가 32x32인 이미지 데이터를 가정하고, 이 배열에 대해 expand_dims를 사용하여 shape (1, 32, 32)로 바꾸는 코드를 작성하세요.
img = np.random.rand(32, 32)
print("✔문제2:", np.expand_dims(arr, axis=0).shape)
# 3. 아래 배열에서 불필요한 1차원을 모두 제거하여 shape이 (28, 28)이 되도록 만드세요.
img = np.random.randint(0, 255, (1, 28, 28, 1))
print("✔문제3:",np.squeeze(img).shape)
# 4. 아래 2차원 배열을 1) 1차원 배열로 만든 후 2) 중복값을 제거한 뒤 shape (1, n)으로 재구성하세요
arr = np.array([[3, 1, 2, 2],
[1, 2, 3, 1],
[2, 2, 1, 4]])
f = arr.flatten()
print("✔문제4\n 1):",f)
print(" 2):",(np.unique(f)).reshape(1,-1))  # 값이 불확실한 것에 -1을 써주면 이전 과정에서 자동으로 계산해줌
# 5. 다음 배열을 shape (10,)로 만든 뒤 고유값 배열을 구하세요.
arr = np.array([[[1], [3], [2], [1], [3], [2], [3], [1], [2], [3]]])
print("✔문제5:", np.unique(np.squeeze(arr)))
# 6. 다음 배열을 1차원 배열로 만든 후 고유값만 추출해서 shape (고유값 개수, 1)인 2차원 배열로 변환하세요.
arr = np.array([ [[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]],
[[3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8]] ]) # shape (2, 3, 4)
f = arr.flatten()
print("✔문제6\n -1차원 배열:\n",f)
u = np.unique(f)
print(" -고유값 추출:\n",u)
re = np.expand_dims(u, axis = 1)
print(" -shape(고유값 개수, 1)인 2차원 배열로 변환:\n",re)

✔문제1
 -r: [10 20 30 40 50 60]
 -f: [10 20 30 40 50 60]
 -r 수정 후: [999  20  30  40  50  60]
 -f 수정 후: [10 20 30 40 50 60]
✔문제2: (1, 3, 2)
✔문제3: (28, 28)
✔문제4
 1): [3 1 2 2 1 2 3 1 2 2 1 4]
 2): [[1 2 3 4]]
✔문제5: [1 2 3]
✔문제6
 -1차원 배열:
 [0 1 2 3 1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7 5 6 7 8]
 -고유값 추출:
 [0 1 2 3 4 5 6 7 8]
 -shape(고유값 개수, 1)인 2차원 배열로 변환:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
# np.concatenate()
# 배열 시퀀스를 결합
# 기존 구조 안에서 결합
a = np.array([[1,2], [3,4]])    # (2,2)
b = np.array([[5,6]])

result1 = np.concatenate((a,b), axis = 0)
print(result1)
print(result1.shape)
print()

# 결합이 불가 → 결합하는 axis를 제외한 나머지 차원이 같아야 함
# result2 = np.concatenate((a,b), axis = 1)

c = np.array([[7], [8], [9]])
result3 = np.concatenate((result1, c), axis = 1)
print(result3)
print(result3.shape)


[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[1 2 7]
 [3 4 8]
 [5 6 9]]
(3, 3)


In [ ]:
# np.stack()
# 새로운 차원을 추가하면서 결합
# 형태가 똑같아야 함.
a = np.array([1,2,3])   # (3,)
b = np.array([4,5,6])

# axis = 0
s1 = np.stack((a,b), axis=0)
print(s1)
print(s1.shape)
print()

# axis = 1
s2 = np.stack((a,b), axis=1)
print(s2)
print(s2.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [82]:
# np.split()
# 배열을 여러개의 하위배열로 분할
a = np.arange(9)
s = np.split(a, 3)
print(a)
print(s)
print(s[0])
print(s[1])
print(s[2])

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[0 1 2]
[3 4 5]
[6 7 8]


In [ ]:
# 배열을 같은 크기로만 나눌 수 있음
a = np.arange(9)
s = np.split(a, 4)

In [91]:
# 인덱스를 활용하여 쪼개면 균등한 크기가 아니라도 동일하게 split 기능을 적용할 수 있음.

print(a)
print()
s1 = np.split(a, [1,3])  # 분할 기준점이 인덱스 1과 3
for part in s1:
    print(part)
print()

s2 = np.split(a, 2, axis = 1)
for part in s2:
    print(part)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [137]:
# 실습. 배열의 결합과 분리
# 1. 다음 두 배열을 행 방향으로 이어붙이세요.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
result = np.concatenate((a,b), axis = 0)
print("문제1:\n", result)
print(result.shape)
print()
# 2. 아래 배열을 3개로 같은 크기로 분할하세요.
a = np.arange(12)
s = np.split(a, 3)
print("문제2:")
for part in s:
    print(part)
print()
# 3. 다음 배열들을 새로운 축에 쌓아 shape이 (3, 2)인 배열을 만드세요.
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
s1 = np.stack((a,b,c), axis=0)
print("문제3:\n", s1)
print(s1.shape)
print()
# 4.  shape가 (2, 3)인 아래 두 배열을 shape (2, 2, 3)인 3차원 배열을 만드세요.
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
s1 = np.stack((a,b), axis=0)
print("문제4:\n", s1)
print(s1.shape)
print()
# 5. 아래의 1차원 배열을 2:3:3 비율(총 3개)로 분할하세요.
arr = np.arange(8)
arr5 = np.split(arr, [2,5])
print("문제5:")
for i, a5 in enumerate(arr5):
    print(a5)
print()
# 6. 아래 두 배열을 axis=0, axis=1로 각각 stack하여 두 경우의 결과 shape을 모두 구하세요
a = np.ones((2, 3))
b = np.zeros((2, 3))
a6 = np.stack([a, b], axis=0)
print("문제6:\n", a6)
b6 = np.stack([a, b], axis=1)
print(b6)

문제1:
 [[1 2]
 [3 4]
 [5 6]]
(3, 2)

문제2:
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]

문제3:
 [[1 2]
 [3 4]
 [5 6]]
(3, 2)

문제4:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)

문제5:
[0 1]
[2 3 4]
[5 6 7]

문제6:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]]


### 3-3. 배열의 정렬

In [113]:
# np.sort(array)
# 정렬된 복사본 반환
# array.sort()
# 원본 배열을 정렬

# 1차원 배열
a = np.array([3,1,4,2])

# 정렬한 배열을 반환
s = np.sort(a)
print(s)
print(a)
print()

# 원본을 정렬
a.sort()
print(a)

# 내림차순 : sort 한 후 배열을 뒤집어야 함.
print(a[::-1])

[1 2 3 4]
[3 1 4 2]

[1 2 3 4]
[4 3 2 1]


In [112]:
# 2차원 배열 정렬
a = [[6,5,4],[3,1,2]]
s1 = np.sort(a, axis=0)
print(s1)
s2 = np.sort(a, axis=1)
print(s2)
print(a)
print()

[[3 1 2]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]
[[6, 5, 4], [3, 1, 2]]



In [115]:
# np.argsort()
# 정렬 인덱스를 반환
a = np.array([3,1,4,2])
idx = np.argsort(a)
print(idx)
print(a[idx])


[1 3 0 2]
[1 2 3 4]


In [ ]:
# 실습. 배열의 정렬
# 1. 아래의 1차원 배열을 오름차순과 내림차순으로 각각 정렬하는 코드를 작성하세요.
arr = np.array([7, 2, 9, 4, 5])
arr.sort()
print(arr)
print(arr[::-1])
print()
# 2. 아래의 2차원 배열에서 각 행(row) 별로 오름차순 정렬된 배열을 구하세요.
arr = np.array([[9, 2, 5],
[3, 8, 1]])
s = np.sort(arr, axis = 1)
print(s)
print()
# 3. 아래의 1차원 배열에서 정렬 결과(오름차순)가 되는 인덱스 배열을 구하고, 그 인덱스를 이용해 원본 배열을 직접 재정렬하는 코드를 작성하세요.
arr = np.array([10, 3, 7, 1, 9])
idx = np.argsort(arr)
print(idx)
print(arr[idx])
print()
# 4. 아래 2차원 배열을 열(column) 기준(axis=0)으로 오름차순 정렬된 배열을 구하세요.
arr = np.array([[4, 7, 2],
                [9, 1, 5],
                [6, 8, 3]])
s = np.sort(arr, axis=0)
print(s)

[2 4 5 7 9]
[9 7 5 4 2]

[[2 5 9]
 [1 3 8]]

[3 1 2 4 0]
[ 1  3  7  9 10]

[[4 1 2]
 [6 7 3]
 [9 8 5]]
